
GET http://localhost:5000/api/test/10
content-type: application/json


###
GET http://localhost:5000/api/ping
content-type: application/json


//while true; do date && curl http://localhost:5000/api/test/1000; echo ""; sleep 1; done